### PR TITLE
Release `v1.1.0`

### PR DESCRIPTION
**Pull request by robbot006**
This is a draft of changelog for the `v1.1.0` release.
Here you can find all related translations changes: [v1.0...main](https://github.com/flarum-lang/dutch/compare/v1.0...main).

> ### ⚠️ Do not merge this pull request manually ⚠️
> 
> You should **[approve](https://github.com/rob006-software/flarum-translations/wiki/How-to-approve-release-pull-request)** this pull request instead. After approving, I will automatically update it (release date needs to be adjusted), merge, and tag a new release. You can read more about the process on [forum](https://discuss.flarum.org/d/20807-simplify-translation-process-with-weblate/76).

<details>
<summary>Show release notes preview</summary>

## v1.1.0

**General changes**:

* Updated Flarum core translations.

**Added support for new extensions**:

* [`afrux/online-users-widget`](https://github.com/afrux/online-users-widget)
* [`antoinefr/flarum-ext-money`](https://github.com/AntoineFr/flarum-ext-money)
* [`antoinefr/flarum-ext-online`](https://github.com/AntoineFr/flarum-ext-online)
* [`askvortsov/flarum-categories`](https://github.com/askvortsov1/flarum-categories)
* [`askvortsov/flarum-checklist`](https://github.com/askvortsov1/flarum-checklist)
* [`askvortsov/flarum-discussion-templates`](https://github.com/askvortsov1/flarum-discussion-templates)
* [`askvortsov/flarum-help-tags`](https://github.com/askvortsov1/flarum-help-tags)
* [`askvortsov/flarum-markdown-tables`](https://github.com/askvortsov1/flarum-markdown-tables)
* [`askvortsov/flarum-pwa`](https://github.com/askvortsov1/flarum-pwa)
* [`askvortsov/flarum-rich-text`](https://github.com/askvortsov1/flarum-rich-text)
* [`askvortsov/flarum-saml`](https://github.com/askvortsov1/flarum-saml)
* [`blomstra/fontawesome`](https://github.com/blomstra/flarum-ext-fontawesome)
* [`blomstra/readme`](https://extiverse.com/extension/blomstra/readme)
* [`clarkwinkelmann/flarum-ext-author-change`](https://github.com/clarkwinkelmann/flarum-ext-author-change)
* [`clarkwinkelmann/flarum-ext-bookmarks`](https://github.com/clarkwinkelmann/flarum-ext-bookmarks)
* [`clarkwinkelmann/catch-the-fish`](https://github.com/clarkwinkelmann/catch-the-fish)
* [`clarkwinkelmann/flarum-ext-create-user-modal`](https://github.com/clarkwinkelmann/flarum-ext-create-user-modal)
* [`clarkwinkelmann/flarum-ext-emojionearea`](https://github.com/clarkwinkelmann/flarum-ext-emojionearea)
* [`clarkwinkelmann/flarum-ext-first-post-approval`](https://github.com/clarkwinkelmann/flarum-ext-first-post-approval)
* [`clarkwinkelmann/flarum-ext-follow-tags-prompt`](https://github.com/clarkwinkelmann/flarum-ext-follow-tags-prompt)
* [`clarkwinkelmann/flarum-ext-group-invitation`](https://github.com/clarkwinkelmann/flarum-ext-group-invitation)
* [`clarkwinkelmann/flarum-ext-group-list`](https://github.com/clarkwinkelmann/flarum-ext-group-list)
* [`clarkwinkelmann/flarum-ext-mailing`](https://github.com/clarkwinkelmann/flarum-ext-mailing)
* [`clarkwinkelmann/flarum-ext-passwordless`](https://github.com/clarkwinkelmann/flarum-ext-passwordless)
* [`clarkwinkelmann/flarum-ext-popular-discussion-badge`](https://github.com/clarkwinkelmann/flarum-ext-popular-discussion-badge)
* [`clarkwinkelmann/flarum-ext-scratchpad`](https://github.com/clarkwinkelmann/flarum-ext-scratchpad)
* [`clarkwinkelmann/flarum-ext-who-read`](https://github.com/clarkwinkelmann/flarum-ext-who-read)
* [`datitisev/flarum-backup`](https://extiverse.com/extension/datitisev/flarum-backup)
* [`datitisev/flarum-maintenance`](https://extiverse.com/extension/datitisev/flarum-maintenance)
* [`datitisev/flarum-webhooks-pro`](https://extiverse.com/extension/datitisev/flarum-webhooks-pro)
* [`datlechin/flarum-signup-button`](https://github.com/datlechin/flarum-signup-button)
* [`datlechin/flarum-usercard-uid`](https://github.com/datlechin/flarum-usercard-uid)
* [`davwheat/custom-sidenav-links`](https://github.com/davwheat/flarum-ext-custom-sidenav-links)
* [`dem13n/discussion-cards`](https://github.com/Dem13n/discussion-cards)
* [`flarumite/simple-discussion-views`](https://github.com/flarumite/simple-discussion-views)
* [`flarumite/simple-spoilers`](https://github.com/flarumite/simple-spoilers)
* [`fof/amazon-affiliation`](https://github.com/FriendsOfFlarum/amazon-affiliation)
* [`fof/analytics`](https://github.com/FriendsOfFlarum/analytics)
* [`fof/byobu`](https://github.com/FriendsOfFlarum/byobu)
* [`fof/cookie-consent`](https://github.com/FriendsOfFlarum/cookie-consent)
* [`fof/custom-footer`](https://github.com/FriendsOfFlarum/custom-footer)
* [`fof/default-group`](https://github.com/FriendsOfFlarum/default-group)
* [`fof/masquerade`](https://github.com/FriendsOfFlarum/masquerade)
* [`fof/username-request`](https://github.com/FriendsOfFlarum/username-request)
* [`webbinaro/flarum-calendar`](https://github.com/eddiewebb/flarum-calendar)

**Updated translations for extensions**:

* [`flarum/akismet`](https://github.com/flarum/akismet)
* [`flarum/likes`](https://github.com/flarum/likes)
* [`flarum/markdown`](https://github.com/flarum/markdown)
* [`flarum/mentions`](https://github.com/flarum/mentions)
* [`flarum/nicknames`](https://github.com/flarum/nicknames)
* [`flarum/statistics`](https://github.com/flarum/statistics)
* [`flarum/suspend`](https://github.com/flarum/suspend)
* [`flarum/tags`](https://github.com/flarum/tags)
* [`fof/best-answer`](https://github.com/FriendsOfFlarum/best-answer)
* [`fof/nightmode`](https://github.com/FriendsOfFlarum/nightmode)
* [`michaelbelgium/flarum-discussion-views`](https://github.com/MichaelBelgium/flarum-discussion-views)
* [`michaelbelgium/mybb-to-flarum`](https://github.com/MichaelBelgium/mybb_to_flarum)
* [`v17development/flarum-blog`](https://github.com/v17development/flarum-blog)

All changes: [v1.0...v1.1.0](https://github.com/flarum-lang/dutch/compare/v1.0...v1.1.0).

</details>

### CODE REVIEW

**Comment by rob006** [comment]
@jaspervriends @MichaelBelgium Just as a note, this is an automated PR generated by bot. The idea is to simplify release process for language pack maintainers - all you need is to approve this pull request and bot will handle the rest. You can read more about the process at forum: https://discuss.flarum.org/d/20807-simplify-translation-process-with-weblate/76 . If you don't want to use this feature, let me know.

**Comment by rob006** [comment]
@jaspervriends @MichaelBelgium It's been over 2 months with no response from you. It is important to tag new releases when new transliterations appear, because by default composer installs only stable versions of packages. It means that all translations added after last release are inaccessible for most of the users. In case of no response from you, I'm going to mark this language pack as unmaintained, so its state will be more clear for users. It means that:
* I'll add info in readme that this language pack is searching for maintainer.
* Command for installing package will use `dev-master` as version, so users will benefit from translations not included in last stable release.
* All translations on Weblate will be marked as unverified, so community will be able to edit them without any restrictions.
* You will keep permissions on Weblate and this repository, but if anyone will volunteer to maintain this language pack, he will replace you as maintainer.

**Comment by MichaelBelgium** [comment]
I was planning to tag a release after this PR was ready/merged, but it's in draft the whole time.

EDIT: yeah an extra maintainer is welcome. This repo is kinda the official language pack so
EDIT2: ok tagged v1.1

**Comment by rob006** [comment]
> I was planning to tag a release after this PR was ready/merged, but it's in draft the whole time.

This is not a problem, you can approve it anyway and bot will merge it. Draft state is mostly to hide "merge" button, since this PR should not be merged manually.

**Review by MichaelBelgium — APPROVED** [review]

**Comment by robbot006** [comment]
Success! Now you can announce new release on [forum](https://discuss.flarum.org/d/18962):

~~~markdown
## Version [`v1.1.0`](https://github.com/flarum-lang/dutch/releases/tag/v1.1.0)

**General changes**:

* Updated Flarum core translations.


**Added support for new extensions**:

* [`afrux/online-users-widget`](https://github.com/afrux/online-users-widget)
* [`antoinefr/flarum-ext-money`](https://github.com/AntoineFr/flarum-ext-money)
* [`antoinefr/flarum-ext-online`](https://github.com/AntoineFr/flarum-ext-online)
* [`askvortsov/flarum-categories`](https://github.com/askvortsov1/flarum-categories)
* [`askvortsov/flarum-checklist`](https://github.com/askvortsov1/flarum-checklist)
* [`askvortsov/flarum-discussion-templates`](https://github.com/askvortsov1/flarum-discussion-templates)
* [`askvortsov/flarum-help-tags`](https://github.com/askvortsov1/flarum-help-tags)
* [`askvortsov/flarum-markdown-tables`](https://github.com/askvortsov1/flarum-markdown-tables)
* [`askvortsov/flarum-pwa`](https://github.com/askvortsov1/flarum-pwa)
* [`askvortsov/flarum-rich-text`](https://github.com/askvortsov1/flarum-rich-text)
* [`askvortsov/flarum-saml`](https://github.com/askvortsov1/flarum-saml)
* [`blomstra/fontawesome`](https://github.com/blomstra/flarum-ext-fontawesome)
* [`blomstra/readme`](https://extiverse.com/extension/blomstra/readme)
* [`clarkwinkelmann/flarum-ext-author-change`](https://github.com/clarkwinkelmann/flarum-ext-author-change)
* [`clarkwinkelmann/flarum-ext-bookmarks`](https://github.com/clarkwinkelmann/flarum-ext-bookmarks)
* [`clarkwinkelmann/catch-the-fish`](https://github.com/clarkwinkelmann/catch-the-fish)
* [`clarkwinkelmann/flarum-ext-create-user-modal`](https://github.com/clarkwinkelmann/flarum-ext-create-user-modal)
* [`clarkwinkelmann/flarum-ext-emojionearea`](https://github.com/clarkwinkelmann/flarum-ext-emojionearea)
* [`clarkwinkelmann/flarum-ext-first-post-approval`](https://github.com/clarkwinkelmann/flarum-ext-first-post-approval)
* [`clarkwinkelmann/flarum-ext-follow-tags-prompt`](https://github.com/clarkwinkelmann/flarum-ext-follow-tags-prompt)
* [`clarkwinkelmann/flarum-ext-group-invitation`](https://github.com/clarkwinkelmann/flarum-ext-group-invitation)
* [`clarkwinkelmann/flarum-ext-group-list`](https://github.com/clarkwinkelmann/flarum-ext-group-list)
* [`clarkwinkelmann/flarum-ext-mailing`](https://github.com/clarkwinkelmann/flarum-ext-mailing)
* [`clarkwinkelmann/flarum-ext-passwordless`](https://github.com/clarkwinkelmann/flarum-ext-passwordless)
* [`clarkwinkelmann/flarum-ext-popular-discussion-badge`](https://github.com/clarkwinkelmann/flarum-ext-popular-discussion-badge)
* [`clarkwinkelmann/flarum-ext-scratchpad`](https://github.com/clarkwinkelmann/flarum-ext-scratchpad)
* [`clarkwinkelmann/flarum-ext-who-read`](https://github.com/clarkwinkelmann/flarum-ext-who-read)
* [`datitisev/flarum-backup`](https://extiverse.com/extension/datitisev/flarum-backup)
* [`datitisev/flarum-maintenance`](https://extiverse.com/extension/datitisev/flarum-maintenance)
* [`datitisev/flarum-webhooks-pro`](https://extiverse.com/extension/datitisev/flarum-webhooks-pro)
* [`datlechin/flarum-signup-button`](https://github.com/datlechin/flarum-signup-button)
* [`datlechin/flarum-usercard-uid`](https://github.com/datlechin/flarum-usercard-uid)
* [`davwheat/custom-sidenav-links`](https://github.com/davwheat/flarum-ext-custom-sidenav-links)
* [`dem13n/discussion-cards`](https://github.com/Dem13n/discussion-cards)
* [`flarumite/simple-discussion-views`](https://github.com/flarumite/simple-discussion-views)
* [`flarumite/simple-spoilers`](https://github.com/flarumite/simple-spoilers)
* [`fof/amazon-affiliation`](https://github.com/FriendsOfFlarum/amazon-affiliation)
* [`fof/analytics`](https://github.com/FriendsOfFlarum/analytics)
* [`fof/byobu`](https://github.com/FriendsOfFlarum/byobu)
* [`fof/cookie-consent`](https://github.com/FriendsOfFlarum/cookie-consent)
* [`fof/custom-footer`](https://github.com/FriendsOfFlarum/custom-footer)
* [`fof/default-group`](https://github.com/FriendsOfFlarum/default-group)
* [`fof/masquerade`](https://github.com/FriendsOfFlarum/masquerade)
* [`fof/username-request`](https://github.com/FriendsOfFlarum/username-request)
* [`webbinaro/flarum-calendar`](https://github.com/eddiewebb/flarum-calendar)


**Updated translations for extensions**:

* [`flarum/akismet`](https://github.com/flarum/akismet)
* [`flarum/likes`](https://github.com/flarum/likes)
* [`flarum/markdown`](https://github.com/flarum/markdown)
* [`flarum/mentions`](https://github.com/flarum/mentions)
* [`flarum/nicknames`](https://github.com/flarum/nicknames)
* [`flarum/statistics`](https://github.com/flarum/statistics)
* [`flarum/suspend`](https://github.com/flarum/suspend)
* [`flarum/tags`](https://github.com/flarum/tags)
* [`fof/best-answer`](https://github.com/FriendsOfFlarum/best-answer)
* [`fof/nightmode`](https://github.com/FriendsOfFlarum/nightmode)
* [`michaelbelgium/flarum-discussion-views`](https://github.com/MichaelBelgium/flarum-discussion-views)
* [`michaelbelgium/mybb-to-flarum`](https://github.com/MichaelBelgium/mybb_to_flarum)
* [`v17development/flarum-blog`](https://github.com/v17development/flarum-blog)


All changes: [v1.0...v1.1.0](https://github.com/flarum-lang/dutch/compare/v1.0...v1.1.0).

In order to update run these commands:

```console
composer update flarum-lang/dutch
php flarum cache:clear
```

~~~

**Comment by rob006** [comment]
@MichaelBelgium I deleted your previous tag, since it would most likely confuse the bot and mess up this PR. Intended workflow since now is to tag new releases by approving PRs like these, so you should not tag releases manually.

**Comment by MichaelBelgium** [comment]
@rob006 Yes I noticed the bot tagged too, and alright 👍

**Comment by rob006** [comment]
As for more maintainers, this language pack already has 2 maintainers, and it should be enough, since main job of maintainers is to verify new translations (anyone can contribute translations through Weblate). If you don't have time to translate, that is fine, we mostly want to avoid situation when community contribute translations through Weblate, but they're never released because maintainers are inactive and there is no one to tag new releases. As long as you will take a look at new translations and approve PR like this from time to time, then it is all good.

**Comment by jaspervriends** [comment]
@rob006 Thanks for the info.  I'll add a reminder for myself every month to take a look at the repository.

Just for verify, only one of us needs to approve a PR of this bot and it's then auto-released, right?

**Comment by rob006** [comment]
> Just for verify, only one of us needs to approve a PR of this bot and it's then auto-released, right?

Yes.

You also should get notification about this PR from GitHub, so you may not need additional reminder, just don't ignore GitHub notification. :)

**Comment by MichaelBelgium** [comment]
> As long as you will take a look at new translations and approve PR like this from time to time, then it is all good.

Yeah I can do that :) 

@jaspervriends I don't think every month is needed, What im gonna do is check it every flarum release, so at least the core translations are up-to-date. I will check translate suggestions at the same time then too

@rob006 At what point does the bot generate a release PR tho? Like after x commits or something?
I just added more core translations cuz there were missing ones because a flarum update

**Comment by rob006** [comment]
> At what point does the bot generate a release PR tho? Like after x commits or something?
> I just added more core translations cuz there were missing ones because a flarum update

It should create it few minutes after pushing new translations from Weblate to this repository. 

Also, don't hesitate to release more often. It is perfectly fine to tag new release with only single fix, there is no need to wait for new Flarum release. The main purpose of this new system is to simplify release process, so maintainers could release more frequently.

**Comment by MichaelBelgium** [comment]
Alright, thanks!

**Pull request merged**
