### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by rob006**
This PR adds complete list of supported extensions. List will be automatically updated by bot when new extension will be translated.

### CODE REVIEW

**Review by MichaelBelgium — APPROVED** [review]

**Comment by rob006** [comment]
Hm, it looks like bot messed up something :/. @MichaelBelgium Please wait for a moment, I'll try to check what happened.

**Comment by MichaelBelgium** [comment]
I guess it's suppose to be in the first PR?

**Comment by rob006** [comment]
Yes, he picked wrong PR. It should ignore this PR completely.

**Comment by rob006** [comment]
@MichaelBelgium OK, it should be fine now, sorry for the trouble.

To be clear: this is regular PR, so you need to merge it manually. 
https://github.com/flarum-lang/dutch/pull/2 is release PR, so approving is enough to tag new release.

**Review by jaspervriends — APPROVED** [review]

**Pull request merged**
